server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mobile_subscriber?characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: ****
    driverClassName: com.mysql.cj.jdbc.Driver

  ## Hibernate Properties
  jpa:
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    #generate-ddl: true
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate.ddl-auto: update
